alleat_django/urls.py
from django.conf.urls import patterns, url, include
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()

from alleat_django import settings

# TO_STUDY: Is 'static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)' necessary if using nginx?

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + patterns('',

   url(r'^admin/', include(admin.site.urls)),
   url(r'^api/', include('alleat_api.urls')),
   url(r'^management/', include('alleat_web_management.urls', namespace='management', app_name='alleat_web_management')),

   # Put your main app in last place to ensure 'not_found' page is displayed only when it must
   url(r'^', include('alleat_web_public.urls')),

   )

alleat_web_management/urls.py
from django.conf.urls import patterns, url

from alleat_web_management.views import (
   DashboardView, AccountsView, AboutView, ItemView, LoginView, RestaurantView, CategoryView,
   ItemDetailView, MenuDetailView, MenuView, AllergensView,
   DocumentationView, AccountsManagementView, PostDetailView, PostListView
)


urlpatterns = patterns('',

   url(r'^login', LoginView.as_view(), name='login'),
   url(r'^dashboard$', DashboardView.as_view(), name='dashboard'),
   url(r'^restaurants$', RestaurantView.as_view(), name='restaurants'),
   url(r'^categories$', CategoryView.as_view(), name='categories'),
   url(r'^menus$', MenuView.as_view(), name='menus'),
   url(r'^menus/(?P<id>[0-9]+)$', MenuDetailView.as_view()),
   url(r'^new-menu', MenuDetailView.as_view(), name='new-menu'),
   url(r'^items$', ItemView.as_view(), name='items'),
   url(r'^items/(?P<id>[0-9]+)$', ItemDetailView.as_view()),
   url(r'^new-item$', ItemDetailView.as_view(), name='new-item'),
   url(r'^accounts$', AccountsView.as_view(), name='accounts'),
   url(r'^about$', AboutView.as_view(), name='about'),
   url(r'^accounts-management', AccountsManagementView.as_view(), name='accounts-management'),
   url(r'^allergens$', AllergensView.as_view(), name='allergens'),
   url(r'^documentation', DocumentationView.as_view(), name='documentation'),
   url(r'^posts$', PostListView.as_view(), name='posts'),
   url(r'^posts/(?P<id>[0-9]+)$', PostDetailView.as_view()),
   url(r'^new-post$', PostDetailView.as_view(), name='new-post'),
   url(r'^logout$', 'alleat_web_management.views.do_logout', name='logout'),

   url(r'^(.*)$', 'alleat_web_management.views.not_found')

   )

xdjango/urls.py
from django.conf.urls import url, include

from rest_framework import routers

from xdjango.contrib.auth import views


router = routers.DefaultRouter()
router.register(r'users', views.UserEmailViewSet)


urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^sessions/$', views.SessionAPIView.as_view()),
    url(r'^one-time-tokens/$', views.OneTimeTokenAPIView.as_view()),
    url(r'^preset/(?P<user_id>\d+)/(?P<token>\w+)', views.ResetView.as_view()),
    url(r'^request-password-reset$', views.RequestResetPasswordView.as_view()),
]

alleat_web_management/views.py
from django.views.generic import View
from django.shortcuts import render, redirect
from django.contrib.auth import logout, login, authenticate

from alleat_web_management.validators import LoginFormValidator
from alleat_web_management.mixins import AWMAdminPanelAccessPermissionRequiredMixin


class LoginView(View):
    def get(self, request):
        user = request.user
        if user and user.has_perm('alleat_api.admin_panel_access'):
            next_url = request.GET.get('next','/')
            return redirect(next_url)

        context = {

        }
        return render(request, "alleat_web_management/login.html", context)

    def post(self, request):
        """
        Gestiona el login de un usuario.
        """
        return do_login(request, "alleat_web_management/login.html", next="/")


class AdministratorView(AWMAdminPanelAccessPermissionRequiredMixin, View):
    def get(self, request):
        context = {

        }
        return render(request, 'alleat_web_management/dashboard.html', context)


class DashboardView(AWMAdminPanelAccessPermissionRequiredMixin, View):
    """
    Dashboard View Controller class.
    """
    def get(self, request):
        context = {

        }
        return render(request, 'alleat_web_management/dashboard.html', context)


class AboutView(AWMAdminPanelAccessPermissionRequiredMixin, View):
    """
    About View controller class.
    """
    def get(self, request):
        context = {

        }
        return render(request, 'alleat_web_management/about.html', context)


class RestaurantView(AWMAdminPanelAccessPermissionRequiredMixin, View):
    def get(self, request):
        context = {

        }
        return render(request, 'alleat_web_management/restaurants.html', context)


class CategoryView(AWMAdminPanelAccessPermissionRequiredMixin, View):
    def get(self, request):
        context = {

        }
        return render(request, 'alleat_web_management/categories.html', context)


class ItemView(AWMAdminPanelAccessPermissionRequiredMixin, View):
    def get(self, request):
        context = {

        }
        return render(request, 'alleat_web_management/items.html', context)


class ItemDetailView(AWMAdminPanelAccessPermissionRequiredMixin, View):
    def get(self, request, **kwargs):
        context = {

        }
        return render(request, 'alleat_web_management/item_detail.html', context)


class MenuView(AWMAdminPanelAccessPermissionRequiredMixin, View):
    def get(self, request):
        context = {

        }
        return render(request, 'alleat_web_management/menus.html', context)


class MenuDetailView(AWMAdminPanelAccessPermissionRequiredMixin, View):
    def get(self, request, **kwargs):
        context = {

        }
        return render(request, 'alleat_web_management/menu_detail.html', context)


class AllergensView(AWMAdminPanelAccessPermissionRequiredMixin, View):
    def get(self, request):
        context = {

        }
        return render(request, 'alleat_web_management/allergens.html', context)


class DocumentationView(AWMAdminPanelAccessPermissionRequiredMixin, View):
    def get(self, request):
        context = {

        }
        return render(request, 'alleat_web_management/documentation.html', context)


class AccountsView(AWMAdminPanelAccessPermissionRequiredMixin, View):
    """
    Accounts View Controller class.
    """
    def get(self, request):
        context = {
        }
        return render(request, 'alleat_web_management/accounts.html', context)


class AccountsManagementView(AWMAdminPanelAccessPermissionRequiredMixin, View):
    """
    Accounts management Controller class.
    """
    def get(self, request):
        context = {
        }
        return render(request, 'alleat_web_management/accounts_management.html', context)


class PostListView(AWMAdminPanelAccessPermissionRequiredMixin, View):
    """
    Post List View Controller class.
    """
    def get(self, request):
        context = {
        }
        return render(request, 'alleat_web_management/posts.html', context)


class PostDetailView(AWMAdminPanelAccessPermissionRequiredMixin, View):
    """
    Post detail Controller class.
    """
    def get(self, request, **kwargs):
        context = {
        }
        return render(request, 'alleat_web_management/post_detail.html', context)


def do_login(request, template, next="/"):
    """
    Handle user login.
    """
    error_messages = []

    form = LoginFormValidator(request.POST)
    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']

        user = authenticate(username=username, password=password)
        if user is None:
            error_messages.append('Nombre de usuario o contrasena incorrecto')
        else:
            if user.is_active:
                login(request, user)
                next_url = request.GET.get('next', next)
                return redirect(next_url)
            else:
                error_messages.append('El usuario no esta activo')

    context = {
        'errors': error_messages,
        'form_validator': form,
    }
    return render(request, template, context)


def not_found(request, word):
    context = {

    }
    return render(request, 'alleat_web_management/404.html', context)


def do_logout(request):
    logout(request)
    return redirect('/')

alleat_web_management/templates/alleat_web_management/includes/add_user.html
<h3>Añadir nuevo administrador</h3>

<form ng-submit="sendInvitation()">
    <div class="input-group">
          <input ng-model="email" type="text" class="form-control" placeholder="Correo electrónico">
          <span class="input-group-btn">
              <button class="btn btn-default" type="submit">Enviar invitación</button>
          </span>
    </div><!-- /input-group -->
</form>

alleat_web_management/templates/alleat_web_management/includes/change_password.html
<h3>Cambiar contraseña</h3>
<form ng-submit="updatePasswordSend()" id="change_password_form" name="change_password_form" ng-controller="personalDataCtrl">
    {% csrf_token %}
    <div class="modal-body form-horizontal">
        <div class="form-group">
            <input id="old-password" ng-model="password.old_password" class="form-control" placeholder="Contraseña actual" type="password" name="current_password">
        </div>
        <div class="form-group">
            <input id="new-password" ng-model="password.new_password" class="form-control" placeholder="Nueva contraseña" type="password" name="new_password">
        </div>
        <div class="form-group">
            <input id="confirm-password" ng-model="password.confirm_password" class="form-control" placeholder="Confirme su nueva contraseña" type="password" name="confirm_password">
        </div>
    </div>

    <div class="form-group">
        <button name="change_password" id="change_password_submit" type="submit" class="btn btn-default">Guardar cambios</button>
    </div>
</form>

alleat_web_management/templates/alleat_web_management/includes/edit_client_list.html
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Correo electrónico</th>
        {% if user.is_superuser %}
            <th>Superusuario</th>
        {% endif %}
            <th>Staff administrativo</th>
            <th>Activo</th>
        </tr>
    </thead>
    <tbody>
            <tr ng-repeat="admin in administrators">
                <td>
                    {% verbatim %}
                        {{ admin.email }}
                    {% endverbatim %}
                </td>
            {% if user.is_superuser %}
                <td>
                    <input onclick="return false;" type="checkbox" ng-model="admin.isSuperuser">
                </td>
            {% endif %}
                <td>
                    <input onclick="return false;" type="checkbox" ng-model="admin.isStaff">
                </td>
                <td>
                    <input onclick="return false;" type="checkbox" ng-model="admin.isActive">
                </td>
            </tr>
    </tbody>
</table>

alleat_web_management/templates/alleat_web_management/includes/menu.html
<ul class="nav" id="side-menu">
    <li>
        <a id="dashboard-menu-item" href="{% url 'alleat_web_management:dashboard' %}"><i class="fa fa-desktop fa-fw"></i> Panel de control</a>
    </li>
    <li>
        <a id="orders-menu-item" href="#"><i class="fa fa-star fa-fw"></i> Mis platos<span class="fa arrow"></span></a>
        <ul class="nav nav-second-level">
            <li>
                <a id="pending-orders-menu-item" href="{% url 'alleat_web_management:items' %}"><i class="fa fa-circle-o fa-fw"></i> Listado de platos </a>
            </li>
            <li>
                <a id="ready-orders-menu-item" href="{% url 'alleat_web_management:menus' %}"><i class="fa fa-check-square-o fa-fw"></i> Menús</a>
            </li>
            <li>
                <a id="cancel-orders-menu-item" href="{% url 'alleat_web_management:categories' %}"><i class="fa fa-tag fa-fw"></i> Categorias</a>
            </li>
        </ul>
        <!-- /.nav-second-level -->
    </li>
    <li>
        <a id="issues-menu-item" href="{% url 'alleat_web_management:restaurants' %}"><i class="fa fa-cutlery fa-fw"></i> Mis restaurantes</a>
    </li>
    <li>
        <a id="accounts-management-menu-item" href="{% url 'alleat_web_management:accounts-management' %}"><i class="fa fa-briefcase fa-fw"></i> Gestión de cuentas</a>
    </li>
    <li>
        <a id="orders-menu-item" href="#"><i class="fa fa-info fa-fw"></i> Ayuda<span class="fa arrow"></span></a>
        <ul class="nav nav-second-level">
            <li>
                <a id="issues-menu-item" href="{% url 'alleat_web_management:allergens' %}"><i class="fa fa-life-ring fa-fw"></i> Listado de alérgenos</a>
            </li>
            <li>
                <a id="about-menu-item" href="{% url 'alleat_web_management:documentation' %}"><i class="fa fa-cubes fa-fw"></i> Documentación</a>
            </li>
        </ul>
        <!-- /.nav-second-level -->
    </li>
    <li>
        <a href="#"><i class="fa fa-thumb-tack fa-fw"></i> Entradas<span class="fa arrow"></span></a>
        <ul class="nav nav-second-level">
            <li>
                <a href="{% url 'alleat_web_management:posts' %}"> Todas las entradas </a>
            </li>
            <li>
                <a href="{% url 'alleat_web_management:new-post' %}"> Añadir nueva</a>
            </li>
        </ul>
        <!-- /.nav-second-level -->
    </li>
</ul>

alleat_web_management/templates/alleat_web_management/includes/top_menu.html
<ul class="nav navbar-top-links navbar-right">

    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">
            <li>
                <a id="account-menu-item" href="{% url 'alleat_web_management:accounts' %}"><i class="fa fa-user fa-fw"></i> Mi cuenta</a>
            </li>
            <li class="divider"></li>
            <li>
                <a id="logout-menu-item" href="{% url 'alleat_web_management:logout' %}"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
            </li>
        </ul>
        <!-- /.dropdown-user -->
    </li>
    <!-- /.dropdown -->
</ul>
<!-- /.navbar-top-links -->