alleat_django/urls.py
from django.conf.urls import patterns, url, include
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()

from alleat_django import settings

# TO_STUDY: Is 'static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)' necessary if using nginx?

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + patterns('',

   url(r'^admin/', include(admin.site.urls)),
   url(r'^api/', include('alleat_api.urls')),
   url(r'^management/', include('alleat_web_management.urls', namespace='management', app_name='alleat_web_management')),

   # Put your main app in last place to ensure 'not_found' page is displayed only when it must
   url(r'^', include('alleat_web_public.urls')),

   )

alleat_web_management/urls.py
from django.conf.urls import patterns, url

from alleat_web_management.views import (
   DashboardView, AccountsView, AboutView, ItemView, LoginView, RestaurantView, CategoryView,
   ItemDetailView, MenuDetailView, MenuView, AllergensView,
   DocumentationView, AccountsManagementView, PostDetailView, PostListView
)


urlpatterns = patterns('',

   url(r'^login', LoginView.as_view(), name='login'),
   url(r'^dashboard$', DashboardView.as_view(), name='dashboard'),
   url(r'^restaurants$', RestaurantView.as_view(), name='restaurants'),
   url(r'^categories$', CategoryView.as_view(), name='categories'),
   url(r'^menus$', MenuView.as_view(), name='menus'),
   url(r'^menus/(?P<id>[0-9]+)$', MenuDetailView.as_view()),
   url(r'^new-menu', MenuDetailView.as_view(), name='new-menu'),
   url(r'^items$', ItemView.as_view(), name='items'),
   url(r'^items/(?P<id>[0-9]+)$', ItemDetailView.as_view()),
   url(r'^new-item$', ItemDetailView.as_view(), name='new-item'),
   url(r'^accounts$', AccountsView.as_view(), name='accounts'),
   url(r'^about$', AboutView.as_view(), name='about'),
   url(r'^accounts-management', AccountsManagementView.as_view(), name='accounts-management'),
   url(r'^allergens$', AllergensView.as_view(), name='allergens'),
   url(r'^documentation', DocumentationView.as_view(), name='documentation'),
   url(r'^posts$', PostListView.as_view(), name='posts'),
   url(r'^posts/(?P<id>[0-9]+)$', PostDetailView.as_view()),
   url(r'^new-post$', PostDetailView.as_view(), name='new-post'),
   url(r'^logout$', 'alleat_web_management.views.do_logout', name='logout'),

   url(r'^(.*)$', 'alleat_web_management.views.not_found')

   )

xdjango/urls.py
from django.conf.urls import url, include

from rest_framework import routers

from xdjango.contrib.auth import views


router = routers.DefaultRouter()
router.register(r'users', views.UserEmailViewSet)


urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^sessions/$', views.SessionAPIView.as_view()),
    url(r'^one-time-tokens/$', views.OneTimeTokenAPIView.as_view()),
    url(r'^preset/(?P<user_id>\d+)/(?P<token>\w+)', views.ResetView.as_view()),
    url(r'^request-password-reset$', views.RequestResetPasswordView.as_view()),
]

alleat_web_management/views.py
from django.views.generic import View
from django.shortcuts import render, redirect
from django.contrib.auth import logout, login, authenticate

from alleat_web_management.validators import LoginFormValidator
from alleat_web_management.mixins import AWMAdminPanelAccessPermissionRequiredMixin


class LoginView(View):
    def get(self, request):
        user = request.user
        if user and user.has_perm('alleat_api.admin_panel_access'):
            next_url = request.GET.get('next','/')
            return redirect(next_url)

        context = {

        }
        return render(request, "alleat_web_management/login.html", context)

    def post(self, request):
        """
        Gestiona el login de un usuario.
        """
        return do_login(request, "alleat_web_management/login.html", next="/")


class AdministratorView(AWMAdminPanelAccessPermissionRequiredMixin, View):
    def get(self, request):
        context = {

        }
        return render(request, 'alleat_web_management/dashboard.html', context)


class DashboardView(AWMAdminPanelAccessPermissionRequiredMixin, View):
    """
    Dashboard View Controller class.
    """
    def get(self, request):
        context = {

        }
        return render(request, 'alleat_web_management/dashboard.html', context)


class AboutView(AWMAdminPanelAccessPermissionRequiredMixin, View):
    """
    About View controller class.
    """
    def get(self, request):
        context = {

        }
        return render(request, 'alleat_web_management/about.html', context)


class RestaurantView(AWMAdminPanelAccessPermissionRequiredMixin, View):
    def get(self, request):
        context = {

        }
        return render(request, 'alleat_web_management/restaurants.html', context)


class CategoryView(AWMAdminPanelAccessPermissionRequiredMixin, View):
    def get(self, request):
        context = {

        }
        return render(request, 'alleat_web_management/categories.html', context)


class ItemView(AWMAdminPanelAccessPermissionRequiredMixin, View):
    def get(self, request):
        context = {

        }
        return render(request, 'alleat_web_management/items.html', context)


class ItemDetailView(AWMAdminPanelAccessPermissionRequiredMixin, View):
    def get(self, request, **kwargs):
        context = {

        }
        return render(request, 'alleat_web_management/item_detail.html', context)


class MenuView(AWMAdminPanelAccessPermissionRequiredMixin, View):
    def get(self, request):
        context = {

        }
        return render(request, 'alleat_web_management/menus.html', context)


class MenuDetailView(AWMAdminPanelAccessPermissionRequiredMixin, View):
    def get(self, request, **kwargs):
        context = {

        }
        return render(request, 'alleat_web_management/menu_detail.html', context)


class AllergensView(AWMAdminPanelAccessPermissionRequiredMixin, View):
    def get(self, request):
        context = {

        }
        return render(request, 'alleat_web_management/allergens.html', context)


class DocumentationView(AWMAdminPanelAccessPermissionRequiredMixin, View):
    def get(self, request):
        context = {

        }
        return render(request, 'alleat_web_management/documentation.html', context)


class AccountsView(AWMAdminPanelAccessPermissionRequiredMixin, View):
    """
    Accounts View Controller class.
    """
    def get(self, request):
        context = {
        }
        return render(request, 'alleat_web_management/accounts.html', context)


class AccountsManagementView(AWMAdminPanelAccessPermissionRequiredMixin, View):
    """
    Accounts management Controller class.
    """
    def get(self, request):
        context = {
        }
        return render(request, 'alleat_web_management/accounts_management.html', context)


class PostListView(AWMAdminPanelAccessPermissionRequiredMixin, View):
    """
    Post List View Controller class.
    """
    def get(self, request):
        context = {
        }
        return render(request, 'alleat_web_management/posts.html', context)


class PostDetailView(AWMAdminPanelAccessPermissionRequiredMixin, View):
    """
    Post detail Controller class.
    """
    def get(self, request, **kwargs):
        context = {
        }
        return render(request, 'alleat_web_management/post_detail.html', context)


def do_login(request, template, next="/"):
    """
    Handle user login.
    """
    error_messages = []

    form = LoginFormValidator(request.POST)
    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']

        user = authenticate(username=username, password=password)
        if user is None:
            error_messages.append('Nombre de usuario o contrasena incorrecto')
        else:
            if user.is_active:
                login(request, user)
                next_url = request.GET.get('next', next)
                return redirect(next_url)
            else:
                error_messages.append('El usuario no esta activo')

    context = {
        'errors': error_messages,
        'form_validator': form,
    }
    return render(request, template, context)


def not_found(request, word):
    context = {

    }
    return render(request, 'alleat_web_management/404.html', context)


def do_logout(request):
    logout(request)
    return redirect('/')

alleat_web_management/templates/alleat_web_management/about.html
{% extends 'alleat_web_management/base.html' %}

{% block html_id %}about{% endblock %}

{% block head_title %} Panel de control {% endblock %}

{% block page_title %} Versión {% endblock %}

{% block page_body_content %}

Admin Panel. Version 1.0
{% endblock %}

alleat_web_management/templates/alleat_web_management/accounts_management.html
{% extends 'alleat_web_management/base.html' %}
{% load staticfiles %}

{% block html_id %}accounts-management{% endblock %}

{% block head_title %} Gestión de cuentas {% endblock %}

{% block page_title %} Gestión de cuentas {% endblock %}

{% block app_js %}

<script type="text/javascript" src="{% static '/static/alleat_web_management/js/app/controllers/accounts-management-ctrl.js' %}"></script>

{% endblock %}

{% block page_body_content %}

<div ng-controller="AccountsManagementCtrl" ng-init="initCtrl()">

    <div class="row">
        <div class="col-lg-6">
            {% include 'alleat_web_management/includes/add_user.html' %}
        </div>
        <div class="col-lg-6">

        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <h3>Administradores</h3>
            {% include 'alleat_web_management/includes/edit_client_list.html' %}
        </div>
    </div>

</div>


{% endblock %}

alleat_web_management/templates/alleat_web_management/base.html
{% load staticfiles %}
{% load i18n %}
{% load humanize %}

<!DOCTYPE html>
<html lang="en" id="{% block html_id %}base{% endblock %}">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block head_title %}My site title{% endblock %}</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="{% static '/static/alleat_web_management/css/bootstrap.min.css' %}" >
    <!-- MetisMenu CSS -->
    <link rel="stylesheet" href="{% static '/static/alleat_web_management/css/metisMenu.min.css' %}">
    <!-- Timeline CSS -->
    <link rel="stylesheet" href="{% static '/static/alleat_web_management/css/timeline.css' %}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static '/static/alleat_web_management/css/sb-admin-2.css' %}">
    <link rel="stylesheet" href="{% static '/static/alleat_web_management/css/filter.css' %}">
    <!-- Morris Charts CSS -->
    <link rel="stylesheet" href="{% static '/static/alleat_web_management/css/morris.min.css' %}">
    <!-- Custom Fonts -->
    <link rel="stylesheet" href="{% static '/static/alleat_web_management/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static '/static/alleat_web_management/css/xtyle.css' %}">
    <link rel="stylesheet" href="{% static '/static/alleat_web_management/css/ng-tags-input.min.css' %}">
    <link rel="stylesheet" href="{% static '/static/alleat_web_management/css/ng-tags-input.bootstrap.min.css' %}">

    <link rel="stylesheet" href="{% static '/static/alleat_web_management/css/alleat.css' %}">

    <!-- ui-notification CSS -->
    <link rel="stylesheet" href="{% static '/static/alleat_web_management/css/angular-ui-notification.css' %}">

    {% block extra_css %}{% endblock %}

    <script type="text/javascript" src="{% static '/static/alleat_web_management/js/jquery-3.1.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/static/alleat_web_management/js/angular.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/static/alleat_web_management/js/angular-cookies.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/static/alleat_web_management/js/angular-animate.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/static/alleat_web_management/js/ui-bootstrap-tpls-2.2.0.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/static/alleat_web_management/js/ng-tags-input.min.js' %}"></script>
    <!-- ui-notification JS -->
    <script type="text/javascript" src="{% static '/static/alleat_web_management/js/angular-ui-notification.min.js' %}"></script>

    <script type="text/javascript" src="{% static '/static/alleat_web_management/js/app/app.js' %}"></script>
    <script type="text/javascript" src="{% static '/static/alleat_web_management/js/app/services.js' %}"></script>
    <!-- Directives -->
    <script type="text/javascript" src="{% static '/static/alleat_web_management/js/app/directives/file-model-directive.js' %}"></script>
    <script type="text/javascript" src="{% static '/static/alleat_web_management/js/app/directives/ng-enter-directive.js' %}"></script>

    {% block app_js %}{% endblock %}

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body ng-app="alleat">

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Togglon</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">AllEat</a>
            </div>
            <!-- /.navbar-header -->

            {% include 'alleat_web_management/includes/top_menu.html' %}

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    {% include 'alleat_web_management/includes/menu.html' %}
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">{% block page_title %}My page title{% endblock %}</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            {% block page_body_content %}{% endblock %}
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->


    <!-- jQuery Version 1.11.0 -->
    <script type="text/javascript" src="{% static '/static/alleat_web_management/js/jquery.min.js' %}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script type="text/javascript" src="{% static '/static/alleat_web_management/js/bootstrap.min.js' %}"></script>
    <!-- Metis Menu Plugin JavaScript -->
    <script type="text/javascript" src="{% static '/static/alleat_web_management/js/metisMenu.min.js' %}"></script>

    <script type="text/javascript" src="{% static '/static/alleat_web_management/js/filter-data.js' %}"></script>
    <!-- Custom Theme JavaScript -->
    <script type="text/javascript" src="{% static '/static/alleat_web_management/js/sb-admin-2.js' %}"></script>
    <script type="text/javascript" src="{% static '/static/alleat_web_management/js/FileSaver.min.js' %}"></script>

    {% block extra_js %}{% endblock %}
    
</body>

</html>

alleat_web_management/templates/alleat_web_management/categories.html
{% extends 'alleat_web_management/base.html' %}
{% load staticfiles %}

{% block html_id %}categories{% endblock %}

{% block head_title %} Listado de categorías {% endblock %}

{% block page_title %} Listado de categorías {% endblock %}

{% block app_js %}

<script type="text/javascript" src="{% static '/static/alleat_web_management/js/app/controllers/categories-ctrl.js' %}"></script>

{% endblock %}

{% block page_breadcrumb %}

{% endblock %}

{% block page_body_content %}

<div ng-controller="CategoriesCtrl" ng-init="initList()">
    <div class="row">
        <div class="col-lg-4">
            <select ng-change="changeSelectedRestaurant(restaurant.pk)" class="form-control" ng-model="restaurant.pk" style="margin-bottom: 20px"
                    ng-options="restaurant.pk as restaurant.name for restaurant in restaurantOptions">
                <option value="" selected>Mis restaurantes</option>
            </select>
        </div>
        <div class="col-lg-8">

        </div>
    </div>
    <div class="row" >
        <div class="col-lg-12">
            <div class="panel panel-default" ng-repeat="category in filterCategories">
                <div class="panel-heading">
                    <input type="text" class="input-readonly" size="50" ng-model="category.alias">

                    <button ng-click="saveCategory(category.pk, category.name, category.alias)" class="btn btn-primary pull-right button-edit"><i class="fa fa-save fa-fw"></i></button>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

alleat_web_management/templates/alleat_web_management/dashboard.html
{% extends 'alleat_web_management/base.html' %}

{% block html_id %}dashboard{% endblock %}

{% block head_title %} Panel de control {% endblock %}

{% block page_title %} Panel de control {% endblock %}

{% block page_body_content %}

<div class="row">
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-user fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">{{ total_clients }}</div>
                        <div>Usuarios</div>
                    </div>
                </div>
            </div>
            <a href="{% url 'alleat_web_management:accounts' %}">
                <div class="panel-footer">
                    <span class="pull-left">Ver detalles</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-green">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-circle-o fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">{{ total_active_products }}</div>
                        <div>Platos</div>
                    </div>
                </div>
            </div>
            <a href="/items">
                <div class="panel-footer">
                    <span class="pull-left">Ver detalles</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-yellow">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-cutlery fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">{{ total_pending_orders }}</div>
                        <div>Restaurantes</div>
                    </div>
                </div>
            </div>
            <a href="{% url 'alleat_web_management:restaurants' %}">
                <div class="panel-footer">
                    <span class="pull-left">Ver detalles</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-red">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-check-square-o fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">{{ total_open_tickets }}</div>
                        <div>Menús</div>
                    </div>
                </div>
            </div>
            <a href="{% url 'alleat_web_management:menus' %}">
                <div class="panel-footer">
                    <span class="pull-left">Ver detalles</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-8">

    </div>
</div>
<!-- /.row -->

{% endblock %}

alleat_web_management/templates/alleat_web_management/documentation.html
{% extends 'alleat_web_management/base.html' %}

{% block html_id %}documentation{% endblock %}

{% block head_title %} Documentación {% endblock %}

{% block page_title %} Documentación {% endblock %}

{% block page_body_content %}
<div class="row">
    <div class="col-lg-12">
       AllEat Beta 2.
    </div>
</div>


{% endblock %}

alleat_web_management/templates/alleat_web_management/item_detail.html
{% extends 'alleat_web_management/base.html' %}
{% load staticfiles %}

{% block html_id %}item-detail{% endblock %}

{% block head_title %} Detalle del plato {% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static '/static/alleat_web_management/css/cropit.css' %}" >
{% endblock %}

{% block page_title %} Detalle del plato {% endblock %}

{% block app_js %}

<script type="text/javascript" src="{% static '/static/alleat_web_management/js/app/controllers/item-ctrl.js' %}"></script>

{% endblock %}

{% block page_body_content %}

<form ng-controller="ItemCtrl" ng-submit="saveItem()" ng-init="initDetail()">
    {% csrf_token %}

    <div class="row">
        <div class="col-lg-6">
            <div class="form-group">
                <input class="form-control" ng-model="item.name" placeholder="Nombre" name="name" id="name">
            </div>
            <div class="form-group">
                <textarea rows="3" cols="40" ng-model="item.description" class="form-control" placeholder="Descripción" name="description" id="description"></textarea>
            </div>
            <div class="form-group">
                <input class="form-control" ng-model="item.price" step="0.01" min="0.01" type="number" placeholder="Precio" name="price" id="price">
            </div>
            <div class="form-group">
                <label>Categorías</label>
                <tags-input ng-model="categoryTags">
                    <auto-complete source="loadTags($query)"></auto-complete>
                </tags-input>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="form-group">
                <select ng-change="loadCategoryTagOptions()" class="form-control" id="category-tag-select" name="restaurant" ng-model="item.restaurant"
                        ng-options="restaurant.pk as restaurant.name for restaurant in restaurantOptions">
                    <option value="" disabled selected>Selecciona mi restaurante</option>
                </select>
            </div>
            <div class="form-group">
                <label>Imagen principal</label>
            </div>

            <div class="image-editor">
              <div class="cropit-image-preview"></div>
              <div class="image-size-label">
                Zoom
              </div>
              <input type="range" class="cropit-image-zoom-input">
              <input id="main-image" file-model="item.main_photo" type="file" class="cropit-image-input" name="image">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <h2>Alérgenos</h2>
                <div class="row" ng-repeat="allergenRow in allergenOptions">
                    <div class="col-lg-3" ng-repeat="allergen in allergenRow">
                        {% verbatim %}
                        <label>{{ allergen.name }}
                            <button uib-popover-html="allergen.possiblyAllergenContentDescriptionHTML" popover-title="Alimentos que pueden contener este alergeno" type="button" class="btn btn-xs btn-warning"><span class="glyphicon glyphicon-exclamation-sign"></span></button>

                            <button uib-popover-html="allergen.allergenContentDescriptionHTML" popover-title="Alimentos que con toda seguridad contienen este alergeno" type="button" class="btn btn-xs btn-danger"><span class="glyphicon glyphicon-ban-circle"></span></button>
                        </label>
                        {% endverbatim %}
                            <select class="form-control" id="category-tag-select" name="allergen" ng-model="allergen.state"
                                    ng-options="state.code as state.displayedName for state in allergenStates">
                            </select>
                        <br>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <button type="submit" class="btn btn-default">Guardar</button>
            <button type="reset" class="btn btn-default">Limpiar informacion</button>
        </div>
    </div>

</form>

{% endblock %}

{% block extra_js %}
    <script src="{% static '/static/alleat_web_management/js/jquery.cropit.js' %}"></script>
    <script src="{% static '/static/alleat_web_management/js/mycropit.js' %}"></script>
{% endblock %}

alleat_web_management/templates/alleat_web_management/menus.html
{% extends 'alleat_web_management/base.html' %}
{% load staticfiles %}

{% block html_id %}menus{% endblock %}

{% block head_title %} Mis menús {% endblock %}

{% block page_title %} Mis menús {% endblock %}

{% block app_js %}

<script type="text/javascript" src="{% static '/static/alleat_web_management/js/app/controllers/menu-ctrl.js' %}"></script>

{% endblock %}

{% block page_body_content %}
<div ng-controller="MenuCtrl" ng-init="initList()">
    <div class="row">
        <div class="col-lg-4">
            <select ng-change="changeSelectedRestaurant(restaurant.pk)" class="form-control" ng-model="restaurant.pk" style="margin-bottom: 20px"
                    ng-options="restaurant.pk as restaurant.name for restaurant in restaurantOptions">
                <option value="" selected>Mis restaurantes</option>
            </select>
        </div>
        <div class="col-lg-8">

        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default" ng-repeat="menu in filterMenus">
                <div class="panel-heading">
                    <input type="text" class="input-readonly" size="50" ng-model="menu.name" readonly>

                    <button ng-click="removeMenu(menu.pk)" class="btn btn-danger pull-right button-edit"><i class="fa fa-remove fa-fw"></i></button>
                    <button ng-click="changeMenu(menu.pk)" class="btn btn-default pull-right button-edit"><i class="fa fa-edit fa-fw"></i></button>
                </div>
            </div>

            <a href="{% url 'alleat_web_management:new-menu' %}" class="btn btn-default pull-right">Añadir nuevo menú</a>
        </div>
    </div>
</div>


{% endblock %}

alleat_web_management/templates/alleat_web_management/posts.html
{% extends 'alleat_web_management/base.html' %}
{% load staticfiles %}

{% block html_id %}posts{% endblock %}

{% block head_title %} Entradas {% endblock %}

{% block app_js %}

<script type="text/javascript" src="{% static '/static/alleat_web_management/js/app/controllers/posts-ctrl.js' %}"></script>

{% endblock %}

{% block page_title %} Entradas {% endblock %}

{% block page_body_content %}
<div ng-controller="PostCtrl" ng-init="initList()">
  <div class="row">
    <div class="col-lg-4">
      <select ng-change="changeSelectedState(state.pk)" class="form-control" ng-model="postState.pk" style="margin-bottom: 20px"
              ng-options="state.id as state.displayName for state in stateOptions.choices">
          <option value="" selected>Estado</option>
      </select>
    </div>
    <div class="col-lg-8">

    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default" ng-repeat="post in posts">
        <div class="panel-heading">
          <input type="text" class="input-readonly" size="50" ng-model="post.title" readonly>

          <button ng-click="updatePost(post.pk)" class="btn btn-default pull-right button-edit"><i class="fa fa-edit fa-fw"></i></button>
          <button popover-placement="top" uib-popover-template="dynamicPopover.templateUrl" type="button" class="btn btn-danger pull-right button-edit"><i class="fa fa-remove fa-fw"></i></button>

        </div>
      </div>

      <script type="text/ng-template" id="myPopoverTemplate.html">
        <div class="form-group text-center">
          <label>¿Estás seguro?</label><br>
          <button ng-click="removePost(post.pk)" class="btn btn-success fa fa-check-circle"></button>
        </div>
      </script>

      <a href="{% url 'alleat_web_management:new-post' %}" class="btn btn-default pull-right">Añadir nueva entrada</a>
    </div>
  </div>

</div>

{% endblock %}